name: conda-env
channels:
  - conda-forge
dependencies:
  - aiohappyeyeballs
  - aiohttp
  - aiosignal
  - annotated-types
  - anyio
  - attrs
  - beautifulsoup4
  - certifi
  - chardet
  - click
  - colorama
  - dnspython
  - email-validator
  - fastapi
  - fastapi-cli
  - frozenlist
  - h11
  - httpcore
  - httptools
  - httpx
  - idna
  - Jinja2
  - markdown-it-py
  - MarkupSafe
  - mdurl
  - multidict
  - pydantic
  - pydantic-core
  - Pygments
  - python-dotenv
  - python-multipart
  - PyYAML
  - requests
  - rich
  - shellingham
  - sniffio
  - soupsieve
  - starlette
  - typer
  - typing_extensions
  - tzdata
  - urllib3
  - uvicorn
  - watchfiles
  - websockets
  - yarl
  - pytest
  - openpyxl
  - termcolor
  - ruff
  - shed
  - black
  - pytest-asyncio
  - selenium
  - sortedcontainers
  - wsproto
  - websocket-client
  - pysocks
  - pycparser
  - outcome
  - cffi
  - trio
  - trio-websocket
