name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build the Docker image
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker build -t my-fastapi-app .
          docker tag my-fastapi-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/my-fastapi-app:$(date +%s)
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-fastapi-app:$(date +%s)
